name: Deployment
on:
  push:
    branches:
      - master
env:
  MONGODB_DB_NAME_global: GLOBAL NAME
jobs:
  test:
    environment: test
    runs-on: ubuntu-latest
    env:
      PORT: 8080
      # MONGODB_CLUSTER_ADDRESS: "cluster0.ntrwp.mongodb.net"
      # MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
    steps:
      - name: Output information
        env:
          stepvariable: stepcheck 
        run: |
          echo "Mongo db name ${{ vars.DB_NAME }}"
          echo "mongo db Password $MONGODB_PASSWORD"
          echo "mongo cluster address ${{ vars.MONGODB_CLUSTER_ADDRES }}"
          echo "port is $PORT"
          echo "global name $MONGODB_DB_NAME_global"
          echo "stepvariable $stepvariable"
