name: Deployment
on:
  push:
    branches:
      - master
env:
  MONGODB_DB_NAME_global: GLOBAL NAME
jobs:
  test:
    # environment: testing
    runs-on: ubuntu-latest
    env:
      PORT: 8080
      MONGODB_CLUSTER_ADDRESS: "cluster0.ntrwp.mongodb.net"
      # MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
    steps:
      - name: Output information
        run: |
          echo "Mongo db user name ${{ vars.MONGODB_DB_NAME }}"
          echo "mongo db Password $MONGODB_PASSWORD"
          echo "mongo cluster address $MONGODB_CLUSTER_ADDRESS"
          echo "port is $PORT"